apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-llm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi  # Specify the storage size
