apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
spec:
  capacity:
    storage: {{ .Values.volumeCapacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  awsElasticBlockStore:
    volumeID: {{ .Values.volumeID }}
    fsType: {{ .Values.fsType }}
