apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-methods: "POST,GET,PUT,DELETE,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST,GET,PUT,DELETE,OPTIONS"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   more_set_headers "Content-Type: text/event-stream";
    #   more_set_headers "Cache-Control: no-cache";
    #   more_set_headers "Connection: keep-alive";
    #   proxy_buffering off;
    #   chunked_transfer_encoding on;
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
    - http:
        paths:
          - path: /respond
            pathType: Prefix
            backend:
              service:
                name: fastapi
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 4200
