apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-methods: "POST,GET,PUT,DELETE,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST,GET,PUT,DELETE,OPTIONS"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /respond
            pathType: Prefix
            backend:
              service:
                name: fastapi
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
