# Use an official Python runtime as a parent image
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# Copy application files
COPY fastapi/main.py /app/main.py

# Expose the port FastAPI runs on
EXPOSE 80
