name: Deploy Basic Server for Testing

on:
  workflow_dispatch:
    inputs:
      provider:
        description: "Select the cloud provider"
        required: true
        type: choice
        options:
          - aws
          - exoscale

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: hello-k8s
      NAMESPACE: default
      REPO: sinan-ozel/iac-private

    steps:
    - uses: actions/checkout@v4


    - name: Authenticate to GitHub
      run: |
        gh auth login --with-token <<< "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        gh run list --repo ${{ env.REPO }} --limit 5

    - name: Download latest pulumi stack outputs artifact
      run: |
        gh run list --repo ${{ env.REPO }} --limit 1 --json databaseId > run.json
        RUN_ID=$(jq -r '.[0].databaseId' run.json)
        gh run download $RUN_ID --repo ${{ env.REPO }} -n pulumi/${{ inputs.provider }}/${{ env.CLUSTER_NAME}}.json

    - name: Connect to Kubernetes
      run: |
        # Use pulumi-stack-outputs to configure kubectl
        kubectl config set-cluster cluster --server=$(cat pulumi/${{ inputs.provider }}/${{ env.CLUSTER_NAME}}.json | jq -r '.kubeconfig.server')
        kubectl config set-credentials user --token=$(cat pulumi/${{ inputs.provider }}/${{ env.CLUSTER_NAME}}.json | jq -r '.kubeconfig.token')
        kubectl config set-context context --cluster=cluster --user=user
        kubectl config use-context context

    - name: List Kubernetes nodes for debugging
      run: |
        kubectl get nodes -o wide