name: Deploy Basic Server for Testing

on:
  workflow_dispatch:
    inputs:
      provider:
        description: "Select the cloud provider"
        required: true
        type: choice
        options:
          - aws
          - exoscale

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      CLUSTER_NAME: hello-k8s
      NAMESPACE: default
      REPO: sinan-ozel/iac-private

    steps:
    - name: Create working directories
      run: |
        mkdir -p repo
        mkdir -p iac

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: repo

    - name: Authenticate to GitHub
      run: |
        gh auth login --with-token <<< "${{ secrets.PERSONAL_ACCESS_TOKEN }}"


    - name: Download latest pulumi stack outputs artifact
      working-directory: iac
      run: |
        gh run download --repo ${{ env.REPO }} --name pulumi-${{ inputs.provider }}-${{ env.CLUSTER_NAME}}
        ls -al
        cat ${{ env.CLUSTER_NAME}}.json

    - name: Extract kubeconfig from JSON
      run: |
        jq -r '.kubeconfig' iac/${{ env.CLUSTER_NAME}}.json > iac/kubeconfig.yaml

        REGION=$(jq -r '.region' iac/${{ env.CLUSTER_NAME}}.json)
        echo "REGION=$REGION" >> $GITHUB_ENV

    - name: Create AWS credentials secret
      if: github.event.inputs.provider == 'aws'
      run: |
        mkdir -p tmp
        printf "[default]\naws_access_key_id=%s\naws_secret_access_key=%s\nregion=%s\n" \
          "${{ secrets.AWS_ACCESS_KEY_ID }}" \
          "${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          "${{ env.REGION }}" > tmp/credentials

        AWS_SHARED_CREDENTIALS_FILE=tmp/credentials aws sts get-caller-identity
        AWS_ACCOUNT_ID=$(AWS_SHARED_CREDENTIALS_FILE=tmp/credentials aws sts get-caller-identity --query Account --output text)
        echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV

        export AWS_SHARED_CREDENTIALS_FILE=$PWD/tmp/credentials
        echo "AWS_SHARED_CREDENTIALS_FILE=$PWD/tmp/credentials" >> $GITHUB_ENV

        if [ -z "$AWS_ACCOUNT_ID" ] || [ "$AWS_ACCOUNT_ID" = "None" ]; then
          echo "Error: AWS_ACCOUNT_ID was not set"
          exit 1
        fi

    - name: Configure AWS credentials
      if: github.event.inputs.provider == 'aws'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.CLUSTER_NAME}}-${{ github.repository_owner }}-${{ github.event.repository.name }}-admin-role
        aws-region: ${{ env.REGION }}

    - name: Connect to Kubernetes
      run: |
        # Use the generated kubeconfig file
        export KUBECONFIG=iac/kubeconfig.yaml

        kubectl --kubeconfig=iac/kubeconfig.yaml config view --raw

    - name: List Kubernetes nodes for debugging
      run: |
        # Use the generated kubeconfig file
        export KUBECONFIG=iac/kubeconfig.yaml

        kubectl --kubeconfig=iac/kubeconfig.yaml get nodes -o wide

    - name: Install ingress controller
      run: |
        export KUBECONFIG=iac/kubeconfig.yaml

        kubectl create namespace ingress-nginx

        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update

        helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx

    - name: Apply the ingress controller service
      run: |
        export KUBECONFIG=iac/kubeconfig.yaml

        kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx
        kubectl apply -f repo/iac/k8s/hello-k8s/hello-world-ingress.yaml
        kubectl get ingress -n default


    - name: Apply Hello World deployment
      run: |
        export KUBECONFIG=iac/kubeconfig.yaml
        kubectl apply -f repo/iac/k8s/hello-k8s/hello-world-deployment.yaml

    - name: Apply Hello World service
      run: |
        export KUBECONFIG=iac/kubeconfig.yaml
        kubectl apply -f repo/iac/k8s/hello-k8s/hello-world-service.yaml

    - name: Wait for service external IP
      run: |
        export KUBECONFIG=iac/kubeconfig.yaml
        echo "Waiting for external IP..."
        for i in {1..30}; do
          IP=$(kubectl get svc hello-world-service -n default -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -n "$IP" ]; then
            echo "Hello World service available at http://$IP"
            exit 0
          fi
          sleep 10
        done
        echo "Timeout waiting for service external IP"
        exit 1
