name: Deploy Basic Server for Testing

on:
  workflow_dispatch:
    inputs:
      provider:
        description: "Select the cloud provider"
        required: true
        type: choice
        options:
          - aws
          - exoscale

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: hello-k8s
      NAMESPACE: default
      REPO: sinan-ozel/iac-private

    steps:
    - name: Create working directories
      run: |
        mkdir -p repo
        mkdir -p iac

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: repo

    - name: Authenticate to GitHub
      run: |
        gh auth login --with-token <<< "${{ secrets.PERSONAL_ACCESS_TOKEN }}"


    - name: Download latest pulumi stack outputs artifact
      working-directory: iac
      run: |
        gh run download --repo ${{ env.REPO }} --name pulumi-${{ inputs.provider }}-${{ env.CLUSTER_NAME}}
        ls -al
        cat ${{ env.CLUSTER_NAME}}.json

    - name: Extract kubeconfig from JSON
      run: |
        jq -r '.kubeconfig' iac/${{ env.CLUSTER_NAME}}.json > iac/kubeconfig.yaml

    - name: Connect to Kubernetes
      run: |
        kubectl --kubeconfig=iac/kubeconfig.yaml config view

    - name: List Kubernetes nodes for debugging
      run: |
        kubectl --kubeconfig=iac/kubeconfig.yaml get nodes -o wide